#!/usr/bin/expect


spawn /usr/java/jdk1.6.0_26/bin/java -jar  /home/nagios/monitoring/libexec/CUSTOM/QUEUES_INFORMATION_VERSION2_LIVE_2_USERPROMOFOUR//jmxterm-1.0-alpha-4-uber.jar  -l 192.168.100.205:3705
expect "Welcome to JMX terminal. Type \"help\" for available commands."
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueueDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueueDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueueDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueueEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueueEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"asyncBillingQueueEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueueDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueueDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueueDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueueEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueueEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"billingOptoutQueueEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueueDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueueDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueueDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueueEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueueEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"chargingQueueEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"creditQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"customerCareQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"eventsQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueueDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueueDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueueDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueueEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueueEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"externalChargingQueueEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueueDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueueDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueueDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueueEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueueEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"moPreprocessQueueEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mosQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"mtsQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueueDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueueDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueueDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueueEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueueEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"onLimitMoSmsQueueEXP\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueue\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueue\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueue\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueueDLQ\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueueDLQ\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueueDLQ\",type=Queue MessageCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueueEXP\",type=Queue ConsumerCount \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueueEXP\",type=Queue MessagesAdded \n"
expect "$>"
send  "get -b org.hornetq:module=JMS,name=\"tknRedeemReqQueueEXP\",type=Queue MessageCount \n"
expect "$>"
send "exit;"
