## OPEN SSH KEYS so can access through SSH with no password

LOCAL_DIRECTORY=/cygdrive/d/CD/BACKUP_CD_INFRA/60/NAGIOS/
REMOTE_SERVER=10.1.1.60
REMOTE_DIRECTORY=/home/nagios/TEMP/
REMOTE_USER=root



rsync -azPv $REMOTE_USER@$REMOTE_SERVER:$REMOTE_DIRECTORY   $LOCAL_DIRECTORY
