#!/bin/bash

SCRIPT_PATH=
PATTERN1=TX
PATTERN2=BULK_INVITATION
PREVIOUSVALUE_FILE=PREVIOUS_VALUE


if [ -f $PREVIOUSVALUE_FILE ]
then
    touch $SCRIPT_PATH/$PREVIOUSVALUE_FILE
    echo 0 > $SCRIPT_PATH/$PREVIOUSVALUE_FILE
fi

